import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Heart, MapPin, MessageCircle, PackageSearch, PenLine } from "lucide-react";
import { whatsappUrl } from "@/lib/whatsapp";
import { ContactForm } from "@/components/contact-form";

export const metadata: Metadata = {
  title: "Contact Us",
  description: "Ask MeeraHini about handmade products, availability, care, and custom requests.",
};

const topics = [
  { icon: PackageSearch, title: "A product caught your eye?", copy: "Ask about a piece, its details, or availability before deciding.", href: "/collections", action: "Browse pieces" },
  { icon: PenLine, title: "A custom idea in mind?", copy: "Tell us what you are imagining and start a conversation.", href: whatsappUrl("Hi MeeraHini! I'd like to discuss a custom request."), action: "Start a chat", external: true },
  { icon: Heart, title: "Need a little guidance?", copy: "We can help you compare pieces and find one that feels right.", href: whatsappUrl("Hi MeeraHini! Could you help me choose a handmade piece?"), action: "Ask us", external: true },
];

export default function ContactPage() {
  return <>
    <section className="contact-hero relative isolate overflow-hidden bg-deep text-white"><div className="contact-hero-flower pointer-events-none absolute -right-20 -top-10 hidden h-[480px] w-[700px] opacity-30 md:block"><Image src="/images/footer-botanical.png" alt="" fill sizes="700px" className="object-contain" /></div><div className="shell relative z-10 grid gap-8 py-12 md:grid-cols-[.55fr_.45fr] md:items-end md:gap-16 md:py-24"><div><p className="eyebrow text-[#d7c9a7]">Contact MeeraHini</p><h1 className="mt-4 max-w-3xl font-serif text-[55px] leading-[.84] tracking-tight md:text-[clamp(5rem,8vw,9rem)]">Let’s make it <em>personal.</em></h1></div><div className="max-w-md md:pb-3"><p className="text-[13px] leading-6 text-white/75 md:text-[16px] md:leading-8">Have a question about a handmade piece? Tell us what you have in mind. We’re happy to help you find the right details.</p><a href={whatsappUrl("Hi MeeraHini! I'd like to know more about your handmade collection.")} target="_blank" rel="noreferrer" className="contact-hero-cta mt-6 inline-flex items-center gap-3 rounded-full px-6 py-3 text-xs font-semibold md:mt-8 md:px-8 md:py-4 md:text-sm"><MessageCircle size={18} /> Chat on WhatsApp <ArrowUpRight size={16} /></a></div></div></section>

    <section className="bg-cream py-12 md:py-24"><div className="shell"><div className="mb-6 md:mb-10"><p className="eyebrow text-forest">How can we help?</p><h2 className="mt-2 font-serif text-[38px] leading-none md:text-[60px]">Every question is welcome.</h2></div><div className="grid gap-3 md:grid-cols-3 md:gap-5">{topics.map(({icon: Icon,title,copy,href,action,external}) => <article key={title} className="contact-topic-card group flex min-h-[220px] flex-col justify-between rounded-[18px] border border-line bg-ivory p-6 md:min-h-[300px] md:p-8"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-full bg-beige text-forest"><Icon size={22} strokeWidth={1.5} /></span><ArrowUpRight size={20} className="text-forest transition-transform duration-300 group-hover:translate-x-1 group-hover:-translate-y-1" /></div><div><h3 className="max-w-xs font-serif text-[27px] leading-none md:text-[32px]">{title}</h3><p className="mt-3 max-w-xs text-[12px] leading-5 text-muted md:text-sm md:leading-6">{copy}</p><Link href={href} target={external ? "_blank" : undefined} rel={external ? "noreferrer" : undefined} className="mt-5 inline-flex items-center gap-2 border-b border-forest pb-1 text-xs font-semibold text-forest">{action} <ArrowRight size={14} /></Link></div></article>)}</div></div></section>

    <section className="bg-ivory py-12 md:py-24"><div className="shell grid gap-10 md:grid-cols-[.9fr_1.1fr] md:items-start md:gap-20"><div className="contact-form-intro md:sticky md:top-24"><p className="eyebrow text-forest">Write to us</p><h2 className="mt-3 max-w-md font-serif text-[43px] leading-[.95] md:text-[70px]">Tell us what you’re looking for.</h2><p className="mt-5 max-w-sm text-[12px] leading-6 text-muted md:mt-7 md:text-sm md:leading-7">Share the details here and continue the conversation in WhatsApp. Your message stays in your hands until you press send.</p><div className="contact-form-photo relative mt-7 hidden aspect-[4/2.5] max-w-md overflow-hidden rounded-[18px] md:block"><Image src="/images/painted-vase.png" alt="Hand painted MeeraHini ceramic vase" fill sizes="35vw" className="object-cover" /></div></div><div className="rounded-[20px] border border-line bg-cream p-5 shadow-soft md:rounded-[28px] md:p-10"><div className="mb-7"><p className="eyebrow text-forest">A note for us</p><h3 className="mt-2 font-serif text-[32px] md:text-[42px]">Start a conversation</h3></div><ContactForm /></div></div></section>

    <section className="bg-beige py-12 md:py-24"><div className="shell grid gap-7 md:grid-cols-[.8fr_1.2fr] md:items-center md:gap-16"><div><p className="eyebrow text-forest">Find us</p><h2 className="mt-3 max-w-md font-serif text-[42px] leading-none md:text-[64px]">A place for the pieces to begin.</h2><p className="mt-5 max-w-md text-[12px] leading-6 text-muted md:text-sm md:leading-7">Our studio address has not been confirmed for this preview. The map is a general view of India and does not mark a MeeraHini location.</p><div className="mt-6 flex items-center gap-3 rounded-xl border border-forest/15 bg-ivory p-4 text-[12px] text-forest md:mt-8"><MapPin size={20} /><span>Studio location details coming soon</span></div></div><div className="map-frame relative overflow-hidden rounded-[20px] border border-line bg-[#d9dfcf] shadow-soft"><iframe title="General map of India; MeeraHini studio location not yet confirmed" src="https://www.openstreetmap.org/export/embed.html?bbox=68.0%2C6.0%2C98.0%2C36.0&layer=mapnik" loading="lazy" referrerPolicy="no-referrer" className="absolute inset-0 h-full w-full border-0" /><span className="absolute bottom-3 left-3 rounded-full bg-ivory/95 px-3 py-1.5 text-[10px] font-semibold text-forest shadow-sm">General map preview · no studio pin</span></div></div></section>

    <section className="bg-ivory py-12 md:py-20"><div className="shell grid gap-7 md:grid-cols-[.45fr_.55fr] md:gap-16"><div><p className="eyebrow text-forest">Before we chat</p><h2 className="mt-2 font-serif text-[38px] leading-none md:text-[58px]">Good to know.</h2></div><div className="divide-y divide-line border-y border-line">{[
      ["How do I enquire about a product?","Open the product page and choose Chat on WhatsApp. The product name and price are included in your draft message."],
      ["Can I ask about a custom request?","Yes. Use the form above, choose Custom request, and describe what you have in mind."],
      ["Does completing the form send a message?","The form opens a WhatsApp draft. You decide whether and when to send it."],
    ].map(([question,answer])=><details key={question} className="faq-item py-4 md:py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-[12px] font-semibold md:text-sm"><span>{question}</span><span className="faq-plus text-lg font-normal text-forest">+</span></summary><p className="faq-answer max-w-xl text-[12px] leading-6 text-muted md:text-sm">{answer}</p></details>)}</div></div></section>
  </>;
}
