import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Heart, Leaf, Sparkles } from "lucide-react";

export const metadata: Metadata = {
  title: "Our Story",
  description: "The MeeraHini point of view: thoughtful pieces, honest texture, and handmade character.",
};

const values = [
  { icon: Heart, title: "A human touch", copy: "Small differences in texture and finish are part of what makes a handmade piece feel personal." },
  { icon: Leaf, title: "Natural character", copy: "We are drawn to warm materials, earthy colour, and objects that sit comfortably in everyday life." },
  { icon: Sparkles, title: "Quiet beauty", copy: "Useful things can also be lovely to look at, hold, and return to every day." },
];

export default function AboutPage() {
  return <>
    <section className="about-hero bg-ivory"><div className="shell grid gap-5 py-5 md:grid-cols-[.85fr_1.15fr] md:items-center md:gap-12 md:py-16">
      <div className="md:pr-5"><p className="eyebrow hidden text-forest md:block">About MeeraHini</p><p className="text-[15px] font-medium md:hidden">About Us</p><h1 className="mt-5 hidden max-w-[570px] font-serif text-[clamp(4rem,6vw,7rem)] leading-[.82] tracking-tight md:block">A little more <em className="font-normal text-forest">meaning</em> in the everyday.</h1><p className="mt-7 hidden max-w-md text-[15px] leading-7 text-muted md:block">An appreciation for pieces that show the beauty of the hand and bring warmth to the places we call home.</p><Link href="/collections" className="about-hero-link mt-8 hidden w-fit items-center gap-2 border-b border-forest pb-1 text-sm font-semibold text-forest md:inline-flex">Explore our collection <ArrowUpRight size={16} /></Link></div>
      <div className="about-hero-image relative aspect-[4/3] overflow-hidden rounded-lg md:aspect-[5/4] md:rounded-[26px]"><Image src="/images/artisan.png" alt="Artisan working on embroidered textile" fill priority sizes="(max-width: 768px) 100vw, 58vw" className="object-cover" /><div className="absolute bottom-4 left-4 rounded-full bg-ivory/90 px-4 py-2 text-[10px] font-semibold text-forest backdrop-blur md:bottom-7 md:left-7 md:text-xs">Handmade with heart</div></div>
      <div className="md:hidden"><h1 className="font-serif text-[31px] leading-none">A story in every stitch.</h1><p className="mt-3 max-w-md text-[12px] leading-5 text-muted">MeeraHini celebrates the texture, patience, and quiet character that make handmade pieces feel personal.</p></div>
    </div></section>

    <section className="bg-cream py-12 md:py-24"><div className="shell grid gap-7 md:grid-cols-[.38fr_.62fr] md:gap-16"><div><p className="eyebrow text-forest">Our point of view</p><div className="mt-4 h-px w-20 bg-forest/40" /></div><div><h2 className="max-w-3xl font-serif text-[37px] leading-[.98] md:text-[66px]">Made with intention. <em className="text-forest">Lived with love.</em></h2><p className="mt-6 max-w-xl text-[12px] leading-6 text-muted md:mt-8 md:text-[15px] md:leading-8">MeeraHini began with a simple thought: the things around us can do more than fill a space. A hand worked surface, an earthy colour, or a familiar texture can make an ordinary moment feel special. This is the spirit behind the collection.</p><p className="mt-4 max-w-xl text-[12px] leading-6 text-muted md:text-[15px] md:leading-8">The collection is an invitation to take your time, notice the little details, and choose the pieces that speak to you.</p></div></div></section>

    <section className="bg-beige py-12 md:py-24"><div className="shell"><div className="mb-7 flex items-end justify-between md:mb-12"><div><p className="eyebrow text-forest">What matters to us</p><h2 className="mt-2 font-serif text-[37px] leading-none md:text-[60px]">Beautiful in the details.</h2></div><span className="hidden font-serif text-[60px] leading-none text-forest/20 md:block">01 — 03</span></div><div className="grid gap-3 md:grid-cols-3 md:gap-5">{values.map(({icon: Icon,title,copy}, index) => <article key={title} className="about-value-card group relative overflow-hidden rounded-[18px] bg-ivory p-6 md:min-h-[310px] md:p-8"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-full bg-beige text-forest md:h-14 md:w-14"><Icon size={24} strokeWidth={1.4} /></span><span className="font-serif text-2xl text-forest/35">0{index+1}</span></div><div className="mt-9 md:mt-20"><h3 className="font-serif text-[27px] leading-none md:text-[34px]">{title}</h3><p className="mt-3 max-w-xs text-[12px] leading-6 text-muted md:text-sm">{copy}</p></div></article>)}</div></div></section>

    <section className="bg-ivory py-12 md:py-24"><div className="shell grid gap-7 md:grid-cols-[1fr_1fr] md:items-center md:gap-16"><div className="about-detail-photo relative aspect-[4/4.5] overflow-hidden rounded-[18px] bg-beige md:aspect-[4/4]"><Image src="/images/embroidered-cushion.png" alt="Close look at floral embroidery on a handmade cushion" fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover" /></div><div className="md:pl-4"><p className="eyebrow text-forest">Texture tells a story</p><h2 className="mt-3 max-w-md font-serif text-[38px] leading-[.95] md:text-[64px]">Look a little closer.</h2><p className="mt-5 max-w-lg text-[12px] leading-6 text-muted md:mt-7 md:text-[15px] md:leading-8">The pleasure of handmade is often in the detail: the irregular rhythm of a stitch, a softly uneven ceramic surface, or the weight of a natural fibre. These are the qualities we love to live with.</p><div className="mt-7 grid grid-cols-2 gap-3 md:mt-10"><div className="relative aspect-[4/3] overflow-hidden rounded-xl"><Image src="/images/painted-vase.png" alt="Hand painted ceramic vase" fill sizes="25vw" className="object-cover" /></div><div className="relative aspect-[4/3] overflow-hidden rounded-xl"><Image src="/images/embroidered-tote.png" alt="Embroidered jute tote" fill sizes="25vw" className="object-cover" /></div></div></div></div></section>

    <section className="about-finale relative overflow-hidden bg-deep py-16 text-center text-white md:py-28"><div className="shell relative z-10"><p className="eyebrow text-[#d7c9a7]">Carry the feeling home</p><h2 className="mx-auto mt-4 max-w-4xl font-serif text-[44px] leading-[.9] md:text-[82px]">Find a piece that feels like <em>you.</em></h2><p className="mx-auto mt-5 max-w-md text-[12px] leading-6 text-white/70 md:text-sm">Explore handmade favourites, save what you love, and ask us about the details.</p><Link href="/collections" className="about-finale-cta mt-7 inline-flex items-center gap-2 rounded-full px-6 py-3 text-[12px] font-semibold md:mt-9 md:px-8 md:py-4 md:text-sm">Explore Collection <ArrowRight size={17} /></Link></div></section>
  </>;
}
