import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, HandHeart, Leaf, Sparkles } from "lucide-react";

export const metadata: Metadata = { title: "Our Story", description: "Discover the thoughtful handmade philosophy behind MeeraHini." };

export default function AboutPage() {
  return <><section className="bg-ivory py-5 md:py-24"><div className="shell text-center"><p className="eyebrow hidden text-forest md:block">Our story</p><h1 className="balance mx-auto hidden max-w-5xl font-serif text-8xl leading-[.88] tracking-tight md:block">Beauty lives in the <em className="font-normal text-forest">human touch.</em></h1><h1 className="text-[16px] font-medium md:hidden">About Us</h1><p className="mx-auto mt-7 hidden max-w-2xl text-[15px] leading-7 text-muted md:block">MeeraHini is an ode to things made slowly—pieces whose texture, variation, and character make everyday spaces feel more personal.</p></div></section><section className="pb-8 md:py-20"><div className="shell grid gap-5 lg:grid-cols-[58%_42%] lg:items-center lg:gap-10"><div className="relative aspect-[4/3] overflow-hidden rounded-lg md:rounded-[28px]"><Image src="/images/artisan.png" alt="An artisan at work in a warm studio" fill priority sizes="58vw" className="object-cover" /></div><div className="lg:-ml-10 lg:bg-cream lg:p-12"><p className="eyebrow hidden text-forest md:block">Why MeeraHini</p><h2 className="mt-2 text-[17px] font-medium md:mt-4 md:font-serif md:text-5xl">Our Story</h2><p className="mt-3 text-[12px] leading-5 text-muted md:mt-6 md:text-sm md:leading-7">MeeraHini was born from a simple belief: what is handmade is not just a product, it is a story, a culture and a connection to the people who create it.</p><p className="mt-3 text-[12px] leading-5 text-muted md:mt-4 md:text-sm md:leading-7">We are drawn to honest materials, patient handwork, and forms that become more beautiful as they settle into daily life.</p></div></div></section><section className="bg-beige py-10 md:py-20"><div className="shell grid gap-6 md:grid-cols-3">{[[HandHeart,"The maker matters","We celebrate evidence of the hand: the quiet variations that make an object singular."],[Leaf,"Warmth over perfection","Natural texture and grounded colour create rooms and rituals that feel lived in."],[Sparkles,"Meaningful everyday","Our favourite pieces are beautiful, useful, and easy to keep close for years."]].map(([Icon,title,copy]) => { const ItemIcon=Icon as typeof Leaf; return <div key={String(title)}><ItemIcon size={22} strokeWidth={1.4} className="text-forest" /><h3 className="mt-3 font-serif text-2xl md:mt-6 md:text-3xl">{String(title)}</h3><p className="mt-2 text-[12px] leading-5 text-muted md:mt-3 md:text-sm md:leading-6">{String(copy)}</p></div>; })}</div></section><section className="py-12 text-center md:py-28"><div className="shell"><h2 className="font-serif text-3xl md:text-6xl">Find something that feels like you.</h2><Link href="/collections" className="mt-6 inline-flex items-center gap-2 rounded-full bg-forest px-5 py-3 text-xs font-semibold text-white md:mt-8 md:px-7 md:py-4 md:text-sm">Explore collection <ArrowRight size={17} /></Link></div></section></>;
}
